{% set version = "0.5.6" %}

package:
  name: nbgrader
  version: {{ version }}

source:
  url: https://github.com/jupyter/nbgrader/archive/v{{ version }}.tar.gz
  sha256: 0fb550158a9a46e39d5315f612387965a9bc01fbafa2e5100bcad836b53cab1e

build:
  number: 0
  # Cannot be noarch b/c of the post/pre scripts.
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - nbgrader = nbgrader.apps.nbgraderapp:main

requirements:
  build:
    - python
    - pip
  run:
    - python
    - sqlalchemy
    - python-dateutil
    - jupyter
    - notebook >=4.2
    - nbconvert >=4.2
    - nbformat
    - traitlets
    - jupyter_core
    - jupyter_client
    - tornado
    - six >=1.9
    - requests
    - jsonschema
    - alembic

test:
  source_files:
    - '*'
  requires:
    - pytest
    - selenium
  imports:
    - nbgrader
  commands:
    - nbgrader -h
    - export USER=$(whoami)  # [not win]
    - pytest -s -rxs -v -m "not (nbextensions)" -k "not (test_submission_dicts or test_notebook_submission_dicts or test_get_submissions or test_get_notebook_submissions or test_get_student_notebook_submissions or test_validate_glob or test_filter_notebook or test_force or test_single_file)"  # [not win]

about:
  home: https://github.com/jupyter/nbgrader
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'A system for assigning and grading Jupyter notebooks'

extra:
  recipe-maintainers:
    - jhamrick
    - lgpage
    - ocefpaf
