{% set version = "0.8.3" %}

package:
  name: nbgrader
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/nbgrader/nbgrader-{{ version }}.tar.gz
  sha256: 609610f3e135372ccaa0f3828fc760cdd12be66cc2e0d987665aa5036e04cfdf

build:
  noarch: python
  number: 0
  script:
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - nbgrader = nbgrader.apps.nbgraderapp:main

requirements:
  host:
    - python >=3.8
    - pip
    - hatchling >=1.10.0
    - hatch-jupyter-builder >=0.7
    - jupyterlab <4
  run:
    - python >=3.8
    - alembic >=1.7
    - ipywidgets >=7.6
    - jinja2 >=3
    - jsonschema >=3
    - jupyter_client <8
    - jupyter_server >=1.12,<2
    - jupyterlab <4
    - jupyterlab_server
    - nbclient >=0.6.1
    - nbconvert >=6
    - notebook >=6.4,<7
    - python-dateutil >=2.8
    - rapidfuzz >=1.8
    - requests >=2.26
    - sqlalchemy >=1.4,<2
    - traitlets >5.0,<6

test:
  imports:
    - nbgrader
  commands:
    - nbgrader -h

about:
  home: https://github.com/jupyter/nbgrader
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A system for assigning and grading Jupyter notebooks

extra:
  recipe-maintainers:
    - blink1073
    - jhamrick
    - lgpage
    - ocefpaf
    - BertR
    - SylvainCorlay
