{% set version = "0.9.4" %}
{% set python_min = python_min | default("3.9") %}

{% set jupyterlab_min = "4.2" %}
{% set jupyterlab_max = "5.0" %}

package:
  name: nbgrader
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/n/nbgrader/nbgrader-{{ version }}.tar.gz
  sha256: 355821170f994c5c361be8af4eb6c189e7f9b210a4e82a1a78fbc4a3ce2290a9

build:
  noarch: python
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
  entry_points:
    - nbgrader = nbgrader.apps.nbgraderapp:main

requirements:
  host:
    - hatch-jupyter-builder >=0.7
    - hatchling >=1.10.0
    - jupyterlab {{ jupyterlab_min }}
    - pip
    - python {{ python_min }}
  run:
    - alembic >=1.7
    - ipython >=8.10.0
    - ipywidgets >=7.6
    - jinja2 >=3
    - jsonschema >=3
    - jupyter_client <9
    - jupyter_server >=2
    - jupyterlab >={{ jupyterlab_min }},<{{ jupyterlab_max }}
    - jupyterlab_server
    - nbclient >=0.6.1
    - nbconvert >=6
    - notebook >=7.2.0,<8
    - python >={{ python_min }}
    - python-dateutil >=2.8
    - pyyaml >=6.0
    - rapidfuzz >=1.8
    - requests >=2.26
    - setuptools
    - sqlalchemy >=1.4,<3

test:
  requires:
    - jupyterlab {{ jupyterlab_min }}
    - m2-grep  # [win]
    - pip
    - python {{ python_min }}
  imports:
    - nbgrader
  commands:
    - pip check
    - nbgrader -h
    - jupyter lab --version
    - jupyter labextension list
    - jupyter server extension list
    - jupyter labextension list 1>labextensions 2>&1
    - jupyter server extension list 1>server_extensions 2>&1
    {% for ext in ["assignment_list", "course_list", "formgrader", "validate_assignment"] %}
    - grep -iE "nbgrader.server_extensions.{{ ext }}.*OK" server_extensions
    - grep -iE "nbgrader.server_extensions.{{ ext }}.*enabled" server_extensions
    {% endfor %}
    - grep -iE "@jupyter/nbgrader.*OK" labextensions

about:
  home: https://github.com/jupyter/nbgrader
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
    - nbgrader/labextension/static/third-party-licenses.json
  summary: A system for assigning and grading Jupyter notebooks
  doc_url: https://nbgrader.readthedocs.io

extra:
  recipe-maintainers:
    - blink1073
    - jhamrick
    - lgpage
    - ocefpaf
    - BertR
    - SylvainCorlay
    - bollwyvl
