{% set gh_org = "jupyter" %}
{% set gh_repo = "nbgrader" %}
{% set version = "v0.4.0" %}
{% set sha256 = "a7170b76eaf493a59ed1e314f0256a55930ecf28c2c1ca4b6896b3ad6dd235d1" %}

package:
  name: {{ gh_repo|lower }}
  version: {{ version }}

source:
  fn: {{ gh_repo }}-{{ version }}.tar.gz
  url: https://github.com/{{ gh_org }}/{{ gh_repo }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - PR695.patch
    - PR700.patch
    - PR701.patch
    - PR704.patch

build:
  number: 1
  skip: true  # [win and py27]

requirements:
  build:
    - jupyter
    - jupyter_client
    - jupyter_core
    - nbconvert >=4.2
    - nbformat
    - notebook >=4.2
    - python
    - python-dateutil
    - requests
    - setuptools
    - six
    - sqlalchemy
    - tornado
    - traitlets

  run:
    - jupyter
    - jupyter_client
    - jupyter_core
    - nbconvert >=4.2
    - nbformat
    - notebook >=4.2
    - python
    - python-dateutil
    - requests
    - six
    - sqlalchemy
    - tornado
    - traitlets

test:
  requires:
    - nodejs
    - notebook >=4.2
    - pytest
    - python
    - requests
    - selenium
    - phantomjs

  source_files:
    - '*'

  imports:
    - nbgrader

about:
  home: https://github.com/{{ gh_org }}/{{ gh_repo }}
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING.md
  summary: A system for assigning and grading Jupyter notebooks.

extra:
  recipe-maintainers:
    - jhamrick
    - lgpage
