{% set version = "0.8.0" %}

package:
  name: nbgrader
  version: {{ version }}

source:
  url: https://github.com/jupyter/nbgrader/archive/v{{ version }}.tar.gz
  sha256: 6362ee2f8fca7ae524823384a03bd35277824429cec09e1640e14d024bd9bda0

build:
  number: 0
  skip: true  # [py<36]
  # Cannot be noarch b/c of the post/pre scripts.
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - nbgrader = nbgrader.apps.nbgraderapp:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - alembic >=1.7
    - ipywidgets >=7.6
    - jinja2 >=3
    - jsonschema >=3
    - jupyter_client <8
    - jupyter_server >=1.12
    - markupsafe <2.2.0
    - nbclient >=0.6.1
    - nbconvert >=6
    - notebook >=6.4,<7
    - python-dateutil >=2.8
    - qtconsole >=5.2
    - rapidfuzz >=1.8
    - requests >=2.26
    - sqlalchemy >=1.4,<2
    - traitlets <5.2.0

test:
  imports:
    - nbgrader
  commands:
    - nbgrader -h

about:
  home: https://github.com/jupyter/nbgrader
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A system for assigning and grading Jupyter notebooks

extra:
  recipe-maintainers:
    - blink1073
    - jhamrick
    - lgpage
    - ocefpaf
    - BertR
    - SylvainCorlay
