{% set version = "0.6.2" %}

package:
  name: nbgrader
  version: {{ version }}

source:
  url: https://github.com/jupyter/nbgrader/archive/v{{ version }}.tar.gz
  sha256: 09a6a79ea07867a844ab5b475e9784319dc441a5bd19ae71f8d853ae196b2180

build:
  number: 2
  # Cannot be noarch b/c of the post/pre scripts.
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - nbgrader = nbgrader.apps.nbgraderapp:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - alembic >=1.7
    - jsonschema >=3.2
    - jupyter
    - jupyter_client >=6.1
    - jupyter_core >=4.7
    - nbconvert >=5.6
    - nbformat >=5.1
    - notebook >=6.4,<7
    - python-dateutil >=2.8.2
    - rapidfuzz >=1.6
    - requests >=2.26
    - six >=1.11
    - sqlalchemy >=1.4
    - tornado >=6.1
    - traitlets >=5.1
        
test:
  imports:
    - nbgrader
  commands:
    - nbgrader -h

about:
  home: https://github.com/jupyter/nbgrader
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A system for assigning and grading Jupyter notebooks

extra:
  recipe-maintainers:
    - blink1073
    - jhamrick
    - lgpage
    - ocefpaf
    - BertR
    - SylvainCorlay
