appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: XqwRp5m5e49NBeo0aASYr4b/8l29CP0WjhmLCNy0aVxMi66NtpRBZ9ab1HbOCAWKe6fMS56QOFgRMO23B/UbKmbBl9hHnV9zWFTFlIAzGhKci7S+1KrA0dvjVHq4dmFcwewjCbpriVUAgNXyTYcf92u2tpOlLTloh0CzQtooMOVPkoU79Wg5hLdbBO+mpDNoG7pw23xvpQQK2dr63nf8w+UWEvwGh9PnxbAQ7YLNcP1Z1PiX2idvLzOdYY6gbIUzhS6WDsgxnLhmXbgvH2bV8OZalXd7Iqyt7MpNp+xsEKwjDu6BCD06uRpUp1TDg2+uW4tfLGTI4i7AXLgfybzY8/Lw5RyBARcLimobGDCfIYv/j8LsA2/sp+0VE2OxQab0a1GE05lnLrxeiWWGKCoL2NWoKQcQX1CvD2uYBQhmwUS6oAKTAWFPK2tMTRhdo0d9PwQUtO41HS+zBNFNJ9Lp8i/aqSJGWIjDhm+uw0GxR/fKnCK0IVzoyNC8JSVGxMcaH9nPj9h9V0OslvpZ41k+iUJet6tncY+5GOKcd+CzLikfwpnc2xxRz3JKtxniD52EVFa0Z3jaXU91mnSCLKstXMM+QVtik/F5oSsTE4Cql5SgdsOLXuNcYb9CFQ03NTzQ+x0BUuN5mS4qQ99IG6Y05o0OWvfXsN2TKQKmBMUrp9w=}
provider:
  win: azure
  linux_aarch64: default
  linux_ppc64le: default
conda_forge_output_validation: true
